#!/usr/bin/env python3
"""
Enrich VaultLingo dictation database with 68+ essential sentences for:
1. High-Frequency IELTS Speaking & Writing Topics (Environment, Education, Tech & Society, Art & Culture, Urban Life)
2. Practical Daily Communication (Dining Out, Shopping & Errands, Housing & Renting, Social Small Talk, Clinic & Healthcare)
"""

import sqlite3
import os

DB_PATHS = [
    os.path.expanduser("~/.local/share/VaultLingo/vocab.db"),
    os.path.abspath(os.path.join(os.path.dirname(__file__), "../backend/data/vocab.db")),
    os.path.abspath(os.path.join(os.path.dirname(__file__), "../data/vocab.db")),
]

IELTS_AND_DAILY_DICTATIONS = [
    # 🌿 1. Environment & Climate Change (IELTS Core) (8 sentences)
    ("B2 IELTS", "#ff9800", "Environment & Climate", "🌿",
     "Transitioning to renewable energy sources such as solar and wind is essential for reducing carbon emissions.",
     "Chuyển đổi sang các nguồn năng lượng tái tạo như mặt trời và gió là điều thiết yếu để cắt giảm khí thải carbon.",
     "Keywords: renewable energy, solar and wind, essential, carbon emissions."),
    ("B2 IELTS", "#ff9800", "Environment & Climate", "🌿",
     "Plastic pollution in oceans poses an existential threat to marine ecosystems and global biodiversity.",
     "Ô nhiễm rác thải nhựa ở các đại dương gây ra mối đe dọa sinh tồn đối với các hệ sinh thái biển và đa dạng sinh học toàn cầu.",
     "Keywords: plastic pollution, oceans, existential threat, marine ecosystems, biodiversity."),
    ("B2 IELTS", "#ff9800", "Environment & Climate", "🌿",
     "Deforestation in tropical rainforests accelerates global warming and destroys critical wildlife habitats.",
     "Nạn phá rừng ở các khu rừng mưa nhiệt đới làm đẩy nhanh hiện tượng ấm lên toàn cầu và phá hủy môi trường sống quan trọng của động vật hoang dã.",
     "Keywords: deforestation, tropical rainforests, accelerates global warming, wildlife habitats."),
    ("B2 IELTS", "#ff9800", "Environment & Climate", "🌿",
     "Governments should introduce stricter environmental regulations and carbon taxes on heavy industrial polluters.",
     "Các chính phủ nên ban hành những quy định môi trường nghiêm ngặt hơn và áp thuế carbon đối với các ngành công nghiệp gây ô nhiễm nặng.",
     "Keywords: stricter regulations, carbon taxes, heavy industrial polluters."),
    ("B1 IELTS", "#4caf50", "Environment & Climate", "🌿",
     "Raising public awareness about waste segregation and recycling helps minimize municipal landfill volume.",
     "Nâng cao nhận thức cộng đồng về phân loại rác và tái chế giúp giảm thiểu khối lượng rác chôn lấp tại đô thị.",
     "Keywords: public awareness, waste segregation, recycling, landfill volume."),
    ("B2 IELTS", "#ff9800", "Environment & Climate", "🌿",
     "Extreme weather events like prolonged droughts and sudden flash floods have become increasingly frequent worldwide.",
     "Các hiện tượng thời tiết cực đoan như hạn hán kéo dài và lũ quét bất ngờ ngày càng trở nên thường xuyên hơn trên toàn thế giới.",
     "Keywords: extreme weather, prolonged droughts, flash floods, increasingly frequent."),
    ("B2 IELTS", "#ff9800", "Environment & Climate", "🌿",
     "Conserving endangered species requires international cooperation and designated protected wildlife reserves.",
     "Bảo tồn các loài có nguy cơ tuyệt chủng đòi hỏi sự hợp tác quốc tế và việc thiết lập các khu bảo tồn thiên nhiên được bảo vệ.",
     "Keywords: conserving endangered species, international cooperation, protected reserves."),
    ("B1 IELTS", "#4caf50", "Environment & Climate", "🌿",
     "Eco-friendly urban architecture encourages public cycling, green rooftops, and energy-efficient building infrastructure.",
     "Kiến trúc đô thị thân thiện với môi trường khuyến khích việc đi xe đạp, mái nhà phủ xanh và hạ tầng tòa nhà tiết kiệm năng lượng.",
     "Keywords: eco-friendly architecture, public cycling, green rooftops, energy-efficient."),

    # 🎓 2. Education & Career (IELTS Core) (8 sentences)
    ("B2 IELTS", "#ff9800", "Education & Career", "🎓",
     "Higher education equips graduates with specialized theoretical knowledge and critical analytical problem-solving skills.",
     "Giáo dục đại học trang bị cho sinh viên tốt nghiệp kiến thức lý thuyết chuyên sâu và kỹ năng phân tích giải quyết vấn đề phản biện.",
     "Keywords: higher education, specialized knowledge, analytical problem-solving skills."),
    ("B1 IELTS", "#4caf50", "Education & Career", "🎓",
     "Vocational training programs offer practical hands-on experience tailored directly to current industry demands.",
     "Các chương trình đào tạo nghề cung cấp kinh nghiệm thực hành thực tế phù hợp trực tiếp với nhu cầu hiện tại của các ngành công nghiệp.",
     "Keywords: vocational training, hands-on experience, tailored directly, industry demands."),
    ("B2 IELTS", "#ff9800", "Education & Career", "🎓",
     "Studying abroad fosters cultural adaptability, global perspectives, and invaluable international networking opportunities.",
     "Đi du học giúp nuôi dưỡng khả năng thích ứng văn hóa, góc nhìn toàn cầu và những cơ hội kết nối mạng lưới quốc tế vô giá.",
     "Keywords: studying abroad, cultural adaptability, global perspectives, networking opportunities."),
    ("B2 IELTS", "#ff9800", "Education & Career", "🎓",
     "Lifelong learning is indispensable for professionals seeking to adapt to rapid workplace technological disruption.",
     "Học tập suốt đời là điều không thể thiếu đối với các chuyên gia muốn thích nghi với sự thay đổi công nghệ nhanh chóng tại nơi làm việc.",
     "Keywords: lifelong learning, indispensable, professionals, technological disruption."),
    ("B1 IELTS", "#4caf50", "Education & Career", "🎓",
     "Online distance learning provides flexible access to quality curriculum for ambitious students in remote regions.",
     "Học tập từ xa trực tuyến mang lại cơ hội tiếp cận linh hoạt với chương trình giảng dạy chất lượng cho học sinh ở vùng sâu vùng xa.",
     "Keywords: distance learning, flexible access, quality curriculum, remote regions."),
    ("B2 IELTS", "#ff9800", "Education & Career", "🎓",
     "Early childhood education plays a fundamental role in shaping cognitive development and emotional resilience.",
     "Giáo dục mầm non đóng vai trò nền tảng trong việc định hình sự phát triển nhận thức và khả năng phục hồi cảm xúc.",
     "Keywords: early childhood education, cognitive development, emotional resilience."),
    ("B2 IELTS", "#ff9800", "Education & Career", "🎓",
     "Standardized academic testing often fails to measure a student's creative intuition and interpersonal collaborative abilities.",
     "Các bài kiểm tra học thuật chuẩn hóa thường không đo lường được trực giác sáng tạo và khả năng hợp tác tương tác giữa người với người của học sinh.",
     "Keywords: standardized testing, fails to measure, creative intuition, collaborative abilities."),
    ("B1 IELTS", "#4caf50", "Education & Career", "🎓",
     "Summer corporate internships bridge the vital gap between classroom theory and professional corporate expectations.",
     "Các kỳ thực tập doanh nghiệp mùa hè giúp thu hẹp khoảng cách quan trọng giữa lý thuyết trên lớp và kỳ vọng công việc chuyên nghiệp.",
     "Keywords: corporate internships, vital gap, classroom theory, professional expectations."),

    # 📱 3. Technology & Society (IELTS Core) (8 sentences)
    ("B2 IELTS", "#ff9800", "Technology & Society", "📱",
     "Excessive social media screen time has been linked to increased anxiety and attention span deterioration among teenagers.",
     "Thời gian sử dụng mạng xã hội quá mức đã được chứng minh có liên hệ với việc gia tăng lo âu và suy giảm độ tập trung ở thanh thiếu niên.",
     "Keywords: excessive screen time, increased anxiety, attention span deterioration."),
    ("B2 IELTS", "#ff9800", "Technology & Society", "📱",
     "Artificial intelligence is revolutionizing healthcare diagnostics, financial forecasting, and automated industrial manufacturing.",
     "Trí tuệ nhân tạo đang tạo ra cuộc cách mạng trong chẩn đoán y tế, dự báo tài chính và sản xuất công nghiệp tự động.",
     "Keywords: artificial intelligence, healthcare diagnostics, financial forecasting, automated manufacturing."),
    ("B1 IELTS", "#4caf50", "Technology & Society", "📱",
     "Digital literacy has become a fundamental prerequisite for participating in modern global economic opportunities.",
     "Kỹ năng số đã trở thành điều kiện tiên quyết nền tảng để tham gia vào các cơ hội kinh tế toàn cầu hiện đại.",
     "Keywords: digital literacy, fundamental prerequisite, global economic opportunities."),
    ("B1 IELTS", "#4caf50", "Technology & Society", "📱",
     "Taking a periodic weekend digital detox helps restore mental clarity and fosters meaningful face-to-face relationships.",
     "Thực hiện ngắt kết nối kỹ thuật số định kỳ vào cuối tuần giúp khôi phục sự sáng suốt tinh thần và nuôi dưỡng các mối quan hệ trực tiếp ý nghĩa.",
     "Keywords: digital detox, mental clarity, meaningful relationships, face-to-face."),
    ("B2 IELTS", "#ff9800", "Technology & Society", "📱",
     "Algorithms tailored for user engagement often create polarized echo chambers that distort online public discourse.",
     "Các thuật toán được thiết kế để tăng tương tác người dùng thường tạo ra các không gian dội âm phân cực, làm sai lệch các cuộc thảo luận xã hội trên mạng.",
     "Keywords: algorithms, user engagement, polarized echo chambers, public discourse."),
    ("B2 IELTS", "#ff9800", "Technology & Society", "📱",
     "Comprehensive data privacy legislation empowers citizens to retain ownership and control over their personal digital footprint.",
     "Luật bảo vệ quyền riêng tư dữ liệu toàn diện trao quyền cho người dân giữ quyền sở hữu và kiểm soát dấu chân kỹ thuật số cá nhân của họ.",
     "Keywords: data privacy legislation, empowers citizens, personal digital footprint."),
    ("B1 IELTS", "#4caf50", "Technology & Society", "📱",
     "Wearable smartwatches allow individuals to monitor their resting heart rate, daily steps, and sleep cycles in real time.",
     "Đồng hồ thông minh đeo tay cho phép mọi người theo dõi nhịp tim khi nghỉ, số bước chân hàng ngày và chu kỳ giấc ngủ theo thời gian thực.",
     "Keywords: wearable smartwatches, resting heart rate, daily steps, sleep cycles."),
    ("B2 IELTS", "#ff9800", "Technology & Society", "📱",
     "The rise of automation presents complex ethical questions regarding job displacement and workforce retraining.",
     "Sự trỗi dậy của tự động hóa đặt ra những câu hỏi đạo đức phức tạp liên quan đến việc thay thế việc làm và đào tạo lại lực lượng lao động.",
     "Keywords: automation, ethical questions, job displacement, workforce retraining."),

    # 🎨 4. Art, Culture & Traditions (IELTS Core) (6 sentences)
    ("B2 IELTS", "#ff9800", "Art & Culture", "🎨",
     "Preserving indigenous handicraft traditions sustains local cultural identity against rapid global homogenization.",
     "Bảo tồn các truyền thống thủ công mỹ nghệ bản địa giúp duy trì bản sắc văn hóa địa phương trước sự đồng hóa toàn cầu nhanh chóng.",
     "Keywords: preserving traditions, indigenous handicrafts, cultural identity, homogenization."),
    ("B2 IELTS", "#ff9800", "Art & Culture", "🎨",
     "Public government subsidies for museums and art galleries guarantee universal access to national cultural heritage.",
     "Các khoản trợ cấp của chính phủ cho bảo tàng và phòng trưng bày nghệ thuật đảm bảo quyền tiếp cận phổ quát tới di sản văn hóa quốc gia.",
     "Keywords: government subsidies, museums and galleries, universal access, cultural heritage."),
    ("B1 IELTS", "#4caf50", "Art & Culture", "🎨",
     "Traditional folk festivals provide a vibrant platform for local communities to celebrate ancestral heritage and solidarity.",
     "Các lễ hội dân gian truyền thống tạo nên sân chơi sống động để các cộng đồng địa phương tôn vinh di sản tổ tiên và tinh thần đoàn kết.",
     "Keywords: traditional festivals, vibrant platform, ancestral heritage, solidarity."),
    ("B2 IELTS", "#ff9800", "Art & Culture", "🎨",
     "Contemporary architects frequently blend minimalist modern aesthetics with sustainable locally sourced timber and stone.",
     "Các kiến trúc sư đương đại thường kết hợp tính thẩm mỹ tối giản hiện đại với vật liệu gỗ và đá bền vững có nguồn gốc địa phương.",
     "Keywords: contemporary architects, minimalist aesthetics, sustainable timber and stone."),
    ("B2 IELTS", "#ff9800", "Art & Culture", "🎨",
     "Classical literature and poetry encapsulate the societal values, moral dilemmas, and collective hopes of bygone eras.",
     "Văn học cổ điển và thơ ca đúc kết những giá trị xã hội, những tình thế tiến thoái lưỡng nan về đạo đức và hy vọng tập thể của các thời đại đã qua.",
     "Keywords: classical literature, societal values, moral dilemmas, bygone eras."),
    ("B1 IELTS", "#4caf50", "Art & Culture", "🎨",
     "International cultural exchange initiatives foster mutual empathy and dismantle long-standing racial and national stereotypes.",
     "Các sáng kiến trao đổi văn hóa quốc tế giúp nuôi dưỡng sự thấu cảm lẫn nhau và xóa bỏ những định kiến lâu đời về chủng tộc và quốc gia.",
     "Keywords: cultural exchange, mutual empathy, dismantle stereotypes."),

    # 🏙️ 5. Urbanization & City Life (IELTS Core) (6 sentences)
    ("B2 IELTS", "#ff9800", "Urbanization & Cities", "🏙️",
     "Unprecedented urbanization creates mounting challenges regarding affordable housing supply and sewage infrastructure.",
     "Đô thị hóa chưa từng có gây ra những thách thức ngày càng lớn liên quan đến nguồn cung nhà ở giá rẻ và hạ tầng thoát nước.",
     "Keywords: urbanization, mounting challenges, affordable housing, infrastructure."),
    ("B1 IELTS", "#4caf50", "Urbanization & Cities", "🏙️",
     "Expanding municipal green corridors and shaded parks improves air quality and encourages outdoor recreational activities.",
     "Mở rộng các hành lang xanh đô thị và công viên có bóng mát giúp cải thiện chất lượng không khí và khuyến khích các hoạt động giải trí ngoài trời.",
     "Keywords: municipal green corridors, shaded parks, air quality, recreational activities."),
    ("B2 IELTS", "#ff9800", "Urbanization & Cities", "🏙️",
     "Gridlock traffic during morning rush hours causes immense economic productivity losses and increases fuel consumption.",
     "Ùn tắc giao thông vào giờ cao điểm buổi sáng gây tổn thất lớn về năng suất kinh tế và làm tăng lượng tiêu thụ nhiên liệu.",
     "Keywords: gridlock traffic, morning rush hours, productivity losses, fuel consumption."),
    ("B2 IELTS", "#ff9800", "Urbanization & Cities", "🏙️",
     "Smart city platforms deploy intelligent traffic lights to alleviate bottleneck congestion and prioritize emergency vehicles.",
     "Các nền tảng thành phố thông minh triển khai đèn giao thông thông minh để giảm ùn tắc tại các nút thắt và ưu tiên xe cứu hộ khẩn cấp.",
     "Keywords: smart city platforms, intelligent traffic lights, bottleneck congestion, emergency vehicles."),
    ("B1 IELTS", "#4caf50", "Urbanization & Cities", "🏙️",
     "Pedestrian-only street zones boost retail sales for small boutique shops while significantly reducing vehicle noise.",
     "Các khu phố đi bộ thúc đẩy doanh thu bán lẻ cho các cửa hàng nhỏ đồng thời giảm đáng kể tiếng ồn phương tiện.",
     "Keywords: pedestrian zones, boost retail sales, boutique shops, reducing vehicle noise."),
    ("B2 IELTS", "#ff9800", "Urbanization & Cities", "🏙️",
     "Striking a harmonious balance between historic preservation and skyline modernization remains a crucial urban planning challenge.",
     "Đạt được sự cân bằng hài hòa giữa việc bảo tồn di tích lịch sử và hiện đại hóa đường chân trời đô thị vẫn là một thách thức quy hoạch then chốt.",
     "Keywords: harmonious balance, historic preservation, skyline modernization, urban planning."),

    # 🍽️ 6. Dining Out & Food Ordering (Daily Communication) (8 sentences)
    ("A2 Daily", "#4caf50", "Dining & Food", "🍽️",
     "Could you please bring us two glasses of iced water and the seasonal dessert menu?",
     "Bạn có thể vui lòng mang cho chúng tôi hai ly nước đá và thực đơn tráng miệng theo mùa được không?",
     "Keywords: bring, iced water, seasonal dessert menu, please."),
    ("B1 Daily", "#4caf50", "Dining & Food", "🍽️",
     "I have a severe peanut allergy, so could you please confirm that this curry contains no traces of nuts?",
     "Tôi bị dị ứng đậu phộng rất nặng, vì vậy bạn có thể vui lòng xác nhận rằng món cà ri này không có chút hạt nào không?",
     "Keywords: peanut allergy, confirm, curry contains no nuts."),
    ("A2 Daily", "#4caf50", "Dining & Food", "🍽️",
     "We are ready to order our main courses, and we would like to split the final bill evenly.",
     "Chúng tôi đã sẵn sàng gọi món chính, và chúng tôi muốn chia đều hóa đơn cuối cùng.",
     "Keywords: ready to order, main courses, split bill evenly."),
    ("B1 Daily", "#4caf50", "Dining & Food", "🍽️",
     "Could you recommend the chef's signature pasta dish or a popular seafood specialty for dinner?",
     "Bạn có thể gợi ý món mì pasta đặc trưng của bếp trưởng hoặc một món hải sản đặc sản được yêu thích cho bữa tối không?",
     "Keywords: chef's signature dish, popular seafood specialty, recommend."),
    ("B1 Daily", "#4caf50", "Dining & Food", "🍽️",
     "I would like my grilled salmon served with steamed asparagus and mashed potatoes on the side.",
     "Tôi muốn món cá hồi nướng của mình được phục vụ kèm với măng tây hấp và khoai tây nghiền để riêng.",
     "Keywords: grilled salmon, steamed asparagus, mashed potatoes on the side."),
    ("A2 Daily", "#4caf50", "Dining & Food", "🍽️",
     "Excuse me, I ordered a hot cappuccino ten minutes ago; could you check on that with the barista?",
     "Xin lỗi, tôi đã gọi một ly cappuccino nóng mười phút trước; bạn có thể kiểm tra lại với thợ pha chế giúp tôi không?",
     "Keywords: cappuccino, ten minutes ago, check with barista."),
    ("B1 Daily", "#4caf50", "Dining & Food", "🍽️",
     "We would like to book a quiet window table for four guests this Friday evening at seven o'clock.",
     "Chúng tôi muốn đặt một bàn yên tĩnh cạnh cửa sổ cho bốn khách vào tối thứ Sáu tuần này lúc bảy giờ.",
     "Keywords: book table, window table, four guests, Friday evening."),
    ("A2 Daily", "#4caf50", "Dining & Food", "🍽️",
     "You can keep the remaining change; thank you very much for your attentive and friendly service tonight.",
     "Bạn cứ giữ lại tiền lẻ thừa nhé; cảm ơn bạn rất nhiều vì sự phục vụ chu đáo và thân thiện tối nay.",
     "Keywords: keep change, thank you, attentive friendly service."),

    # 🛒 7. Shopping & Errands (Daily Communication) (6 sentences)
    ("A2 Daily", "#4caf50", "Shopping & Supermarket", "🛒",
     "Excuse me, in which aisle can I find gluten-free bread and organic oat milk?",
     "Xin lỗi, tôi có thể tìm thấy bánh mì không chứa gluten và sữa yến mạch hữu cơ ở lối đi nào?",
     "Keywords: which aisle, gluten-free bread, organic oat milk."),
    ("B1 Daily", "#4caf50", "Shopping & Supermarket", "🛒",
     "Do you happen to have this waterproof winter jacket in size medium and forest green color in the back stockroom?",
     "Cửa hàng có còn chiếc áo khoác mùa đông chống nước này cỡ M màu xanh rêu trong kho phía sau không?",
     "Keywords: waterproof winter jacket, size medium, forest green, stockroom."),
    ("B1 Daily", "#4caf50", "Shopping & Supermarket", "🛒",
     "Can I exchange this item for store credit within thirty days if I present the original sales receipt?",
     "Tôi có thể đổi sản phẩm này lấy điểm mua hàng trong vòng ba mươi ngày nếu xuất trình hóa đơn gốc không?",
     "Keywords: exchange item, store credit, thirty days, original sales receipt."),
    ("A2 Daily", "#4caf50", "Shopping & Supermarket", "🛒",
     "Is there any special holiday discount available if I register for your store loyalty membership card today?",
     "Có chương trình giảm giá dịp lễ đặc biệt nào nếu tôi đăng ký thẻ thành viên thân thiết của cửa hàng hôm nay không?",
     "Keywords: holiday discount, register, store loyalty membership card."),
    ("B1 Daily", "#4caf50", "Shopping & Supermarket", "🛒",
     "I need to return this electric kettle because the automatic boiling switch is not functioning properly.",
     "Tôi cần trả lại chiếc ấm đun nước điện này vì công tắc tự ngắt khi sôi không hoạt động bình thường.",
     "Keywords: return electric kettle, automatic boiling switch, not functioning."),
    ("A2 Daily", "#4caf50", "Shopping & Supermarket", "🛒",
     "Please do not include a single-use plastic bag; I brought my own foldable canvas grocery bag.",
     "Làm ơn đừng lấy túi nilon dùng một lần; tôi đã mang theo túi vải bạt có thể gấp gọn của mình rồi.",
     "Keywords: single-use plastic bag, foldable canvas grocery bag."),

    # 🏠 8. Housing & Neighborhood (Daily Communication) (6 sentences)
    ("B1 Daily", "#4caf50", "Housing & Living", "🏠",
     "The neighbor above our apartment plays loud video games past midnight, which constantly disrupts our sleep.",
     "Người hàng xóm phía trên căn hộ của chúng tôi bật loa chơi điện tử ồn ào quá nửa đêm, liên tục làm phiền giấc ngủ của chúng tôi.",
     "Keywords: neighbor above, loud video games, past midnight, disrupts sleep."),
    ("B1 Daily", "#4caf50", "Housing & Living", "🏠",
     "Could the building property manager send a plumber to inspect the persistent drainage issue in our bathroom?",
     "Ban quản lý tòa nhà có thể cử thợ sửa ống nước đến kiểm tra sự cố thoát nước kéo dài trong phòng tắm của chúng tôi được không?",
     "Keywords: property manager, send plumber, persistent drainage issue, bathroom."),
    ("B2 Daily", "#4caf50", "Housing & Living", "🏠",
     "The rental contract stipulates a two-month security deposit and one month written advance notice prior to termination.",
     "Hợp đồng thuê nhà quy định khoản đặt cọc hai tháng và phải thông báo bằng văn bản trước một tháng khi chấm dứt hợp đồng.",
     "Keywords: rental contract stipulates, security deposit, advance notice, termination."),
    ("A2 Daily", "#4caf50", "Housing & Living", "🏠",
     "Our residential neighborhood is exceptionally safe, quiet, and within walking distance of the central metro station.",
     "Khu dân cư của chúng tôi đặc biệt an toàn, yên tĩnh và chỉ cách ga tàu điện ngầm trung tâm một quãng đi bộ ngắn.",
     "Keywords: residential neighborhood, safe quiet, walking distance, metro station."),
    ("A2 Daily", "#4caf50", "Housing & Living", "🏠",
     "Please remember to double-check that the apartment front door is locked whenever you leave for work.",
     "Hãy nhớ kiểm tra kỹ lại xem cửa chính căn hộ đã được khóa chưa mỗi khi bạn đi làm nhé.",
     "Keywords: double-check, front door is locked, leave for work."),
    ("B1 Daily", "#4caf50", "Housing & Living", "🏠",
     "The living room air conditioning unit requires seasonal maintenance because it is blowing warm air instead of cold.",
     "Cục điều hòa phòng khách cần được bảo dưỡng theo mùa vì nó đang thổi ra hơi ấm thay vì hơi mát.",
     "Keywords: air conditioning unit, seasonal maintenance, blowing warm air."),

    # 🤝 9. Small Talk & Socializing (Daily Communication) (6 sentences)
    ("A2 Daily", "#4caf50", "Small Talk & Social", "🤝",
     "How was your weekend trip to the coast? Did you manage to catch good weather while you were there?",
     "Chuyến đi cuối tuần ra bờ biển của bạn thế nào? Bạn có gặp thời tiết đẹp khi ở đó không?",
     "Keywords: weekend trip to coast, catch good weather, while there."),
    ("A2 Daily", "#4caf50", "Small Talk & Social", "🤝",
     "The weather forecast predicted heavy thunderstorms later this evening, so make sure you carry your raincoat.",
     "Dự báo thời tiết cho biết sẽ có dông bão lớn vào chiều tối nay, vì vậy hãy nhớ mang theo áo mưa nhé.",
     "Keywords: weather forecast, heavy thunderstorms, carry raincoat."),
    ("A2 Daily", "#4caf50", "Small Talk & Social", "🤝",
     "Have you tried that cozy artisan bakery down the street? Their fresh croissants are absolutely sensational.",
     "Bạn đã thử tiệm bánh thủ công ấm cúng ở cuối phố chưa? Những chiếc bánh sừng bò tươi ở đó thực sự rất tuyệt vời.",
     "Keywords: artisan bakery down street, fresh croissants, absolutely sensational."),
    ("B1 Daily", "#4caf50", "Small Talk & Social", "🤝",
     "I am looking forward to exploring the botanical gardens this Saturday morning with a couple of close friends.",
     "Tôi rất mong chờ chuyến khám phá vườn bách thảo vào sáng thứ Bảy này cùng với một vài người bạn thân.",
     "Keywords: looking forward to, exploring botanical gardens, close friends."),
    ("A2 Daily", "#4caf50", "Small Talk & Social", "🤝",
     "It was truly wonderful catching up with you today; let us arrange a dinner get-together sometime next month!",
     "Hôm nay thật sự rất vui khi được gặp và trò chuyện cùng bạn; chúng ta hãy hẹn nhau ăn tối vào tháng sau nhé!",
     "Keywords: wonderful catching up, arrange dinner get-together, next month."),
    ("B1 Daily", "#4caf50", "Small Talk & Social", "🤝",
     "Congratulations on completing your master's degree dissertation; your tireless effort over the past year was truly inspiring.",
     "Chúc mừng bạn đã hoàn thành luận văn thạc sĩ; nỗ lực không biết mệt mỏi của bạn trong năm qua thực sự rất truyền cảm hứng.",
     "Keywords: congratulations, master's degree dissertation, tireless effort, inspiring."),

    # 🩺 10. Clinic & Healthcare (Daily Communication) (6 sentences)
    ("B1 Daily", "#4caf50", "Clinic & Healthcare", "🩺",
     "I have been feeling dizzy and suffering from a severe dry cough accompanied by a mild fever since yesterday.",
     "Tôi cảm thấy chóng mặt và bị ho khan dữ dội kèm theo sốt nhẹ từ hôm qua đến nay.",
     "Keywords: feeling dizzy, severe dry cough, mild fever, since yesterday."),
    ("B1 Daily", "#4caf50", "Clinic & Healthcare", "🩺",
     "Please take two capsules with a full glass of water after your evening meal for five consecutive days.",
     "Vui lòng uống hai viên nang với một ly nước đầy sau bữa ăn tối trong năm ngày liên tiếp.",
     "Keywords: two capsules, full glass of water, evening meal, consecutive days."),
    ("A2 Daily", "#4caf50", "Clinic & Healthcare", "🩺",
     "I would like to make an appointment for a general routine dental cleaning and examination next Wednesday morning.",
     "Tôi muốn đặt lịch hẹn để lấy cao răng và kiểm tra răng miệng định kỳ vào sáng thứ Tư tuần sau.",
     "Keywords: make an appointment, dental cleaning, examination, Wednesday morning."),
    ("B1 Daily", "#4caf50", "Clinic & Healthcare", "🩺",
     "Getting at least eight hours of restful sleep each night is critical for strengthening your immune defense system.",
     "Ngủ đủ giấc ít nhất tám tiếng mỗi đêm là điều vô cùng quan trọng để tăng cường hệ thống phòng thủ miễn dịch của bạn.",
     "Keywords: eight hours restful sleep, critical, strengthening immune system."),
    ("B2 Daily", "#4caf50", "Clinic & Healthcare", "🩺",
     "The attending physician recommended scheduling a follow-up blood test to monitor cholesterol levels in three months.",
     "Bác sĩ điều trị đã khuyên nên lên lịch xét nghiệm máu tái khám để theo dõi mức cholesterol trong ba tháng tới.",
     "Keywords: attending physician, follow-up blood test, monitor cholesterol levels."),
    ("B1 Daily", "#4caf50", "Clinic & Healthcare", "🩺",
     "Do you have any severe adverse allergic reactions to specific medications or over-the-counter pain relievers?",
     "Bạn có phản ứng dị ứng nghiêm trọng nào đối với các loại thuốc cụ thể hoặc thuốc giảm đau không kê đơn không?",
     "Keywords: severe allergic reactions, specific medications, over-the-counter pain relievers.")
]

def enrich_databases():
    for db_path in DB_PATHS:
        if not os.path.exists(db_path):
            print(f"⚠️ Skip: {db_path} not found.")
            continue

        print(f"\n🚀 Populating database: {db_path}")
        conn = sqlite3.connect(db_path)
        c = conn.cursor()

        inserted = 0
        for item in IELTS_AND_DAILY_DICTATIONS:
            c.execute("""
                INSERT OR IGNORE INTO dictations (level, level_color, category, category_icon, sentence, sentence_vi, hint)
                VALUES (?, ?, ?, ?, ?, ?, ?)
            """, item)
            if c.rowcount > 0:
                inserted += 1

        conn.commit()

        c.execute("SELECT count(*) FROM dictations")
        total = c.fetchone()[0]

        print(f"✅ Added {inserted} new IELTS & Daily communication sentences! (Total now: {total})")
        conn.close()

if __name__ == "__main__":
    enrich_databases()
    print("\n🎉 Completed IELTS & Daily Communication Dictation enrichment!")
