// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CheckDictation(arg1, arg2) {
  return window['go']['main']['App']['CheckDictation'](arg1, arg2);
}

export function EvaluateWriting(arg1, arg2, arg3) {
  return window['go']['main']['App']['EvaluateWriting'](arg1, arg2, arg3);
}

export function GetAvailableTopics() {
  return window['go']['main']['App']['GetAvailableTopics']();
}

export function GetConfig() {
  return window['go']['main']['App']['GetConfig']();
}

export function GetDailyIdiom() {
  return window['go']['main']['App']['GetDailyIdiom']();
}

export function GetDailyVocab(arg1, arg2) {
  return window['go']['main']['App']['GetDailyVocab'](arg1, arg2);
}

export function GetDictationSentence(arg1) {
  return window['go']['main']['App']['GetDictationSentence'](arg1);
}

export function GetQuickQuiz() {
  return window['go']['main']['App']['GetQuickQuiz']();
}

export function GetSavedObsidianVocab() {
  return window['go']['main']['App']['GetSavedObsidianVocab']();
}

export function GetWritingPrompt(arg1) {
  return window['go']['main']['App']['GetWritingPrompt'](arg1);
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function OpenInObsidian(arg1) {
  return window['go']['main']['App']['OpenInObsidian'](arg1);
}

export function RecordSrsReview(arg1, arg2) {
  return window['go']['main']['App']['RecordSrsReview'](arg1, arg2);
}

export function SaveAllWordsToObsidian(arg1) {
  return window['go']['main']['App']['SaveAllWordsToObsidian'](arg1);
}

export function SaveConfig(arg1) {
  return window['go']['main']['App']['SaveConfig'](arg1);
}

export function SaveWordToObsidian(arg1) {
  return window['go']['main']['App']['SaveWordToObsidian'](arg1);
}

export function SaveWritingToObsidian(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['SaveWritingToObsidian'](arg1, arg2, arg3, arg4, arg5);
}

export function UpdateObsidianSrsReview(arg1, arg2, arg3) {
  return window['go']['main']['App']['UpdateObsidianSrsReview'](arg1, arg2, arg3);
}
