// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {backend} from '../models';

export function AddMockScore(arg1:string,arg2:number,arg3:string):Promise<void>;

export function CheckDictation(arg1:string,arg2:string):Promise<backend.DictationResult>;

export function CheckGrammarAnswer(arg1:string,arg2:string):Promise<backend.DictationResult>;

export function CheckReadingAnswers(arg1:number,arg2:Array<backend.ReadingAnswerInput>):Promise<backend.ReadingResult>;

export function DeleteMockScore(arg1:number):Promise<void>;

export function DeleteWordFromObsidian(arg1:string):Promise<boolean>;

export function EnhanceWriting(arg1:string,arg2:string):Promise<string>;

export function EvaluateSpeaking(arg1:string,arg2:number,arg3:string,arg4:string,arg5:number):Promise<string>;

export function EvaluateWriting(arg1:string,arg2:string,arg3:string):Promise<string>;

export function GetAvailableTopics():Promise<Array<Record<string, string>>>;

export function GetConfig():Promise<backend.Config>;

export function GetDailyIdiom():Promise<backend.Idiom>;

export function GetDailyVocab(arg1:string,arg2:number):Promise<Array<backend.Word>>;

export function GetDictationCategories():Promise<Array<backend.DictationCategoryInfo>>;

export function GetDictationLevels():Promise<Array<backend.DictationLevelInfo>>;

export function GetDictationSentence(arg1:string):Promise<backend.Dictation>;

export function GetDictationSentenceFiltered(arg1:string,arg2:string,arg3:Array<number>):Promise<backend.Dictation>;

export function GetDictationSentenceWithExclude(arg1:string,arg2:Array<number>):Promise<backend.Dictation>;

export function GetGrammarCategories():Promise<Array<backend.GrammarCategoryInfo>>;

export function GetGrammarDrill(arg1:string,arg2:string,arg3:Array<number>):Promise<backend.GrammarDrill>;

export function GetListeningTopics():Promise<Array<backend.ListeningTopic>>;

export function GetMockScores():Promise<Array<backend.MockScore>>;

export function GetOpencodeModels():Promise<Array<backend.OpencodeModelItem>>;

export function GetOpencodeStatus():Promise<backend.OpencodeStatus>;

export function GetQuickQuiz():Promise<backend.Quiz>;

export function GetQuickQuizExcluding(arg1:Array<number>):Promise<backend.Quiz>;

export function GetReadingPassage(arg1:number):Promise<backend.ReadingPassage>;

export function GetReadingPassages():Promise<Array<backend.ReadingPassageMeta>>;

export function GetRecordingStatus():Promise<backend.RecordingStatus>;

export function GetRoadmapProgress():Promise<Record<number, backend.RoadmapProgress>>;

export function GetSavedObsidianVocab():Promise<Array<backend.ObsidianItem>>;

export function GetSpeakingAttempts(arg1:number):Promise<Array<backend.SpeakingAttempt>>;

export function GetSpeakingPrompts(arg1:number,arg2:string):Promise<Array<backend.SpeakingPrompt>>;

export function GetSpeakingTopics():Promise<Array<string>>;

export function GetVoicesList():Promise<Array<backend.VoiceOption>>;

export function GetWordCount():Promise<number>;

export function GetWritingPrompt(arg1:string):Promise<backend.WritingPrompt>;

export function Greet(arg1:string):Promise<string>;

export function LookupWordInDB(arg1:string):Promise<backend.Word>;

export function MarkSession(arg1:number,arg2:string,arg3:string):Promise<void>;

export function OpenInObsidian(arg1:string):Promise<void>;

export function PlayAudioUrl(arg1:string,arg2:number):Promise<void>;

export function PlayTTS(arg1:string,arg2:number):Promise<void>;

export function QueryAI(arg1:string,arg2:string):Promise<string>;

export function RecordSrsReview(arg1:number,arg2:number):Promise<void>;

export function RefreshOpencodeModels():Promise<backend.OpencodeStatus>;

export function SaveAllWordsToObsidian(arg1:Array<backend.Word>):Promise<Array<backend.ObsidianSaveResult>>;

export function SaveConfig(arg1:backend.Config):Promise<void>;

export function SaveSpeakingAttempt(arg1:number,arg2:string,arg3:number,arg4:string):Promise<void>;

export function SaveTranslationToObsidian(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string,arg6:Array<backend.ExtractedVocab>):Promise<backend.ObsidianSaveResult>;

export function SaveWordToDB(arg1:backend.Word):Promise<void>;

export function SaveWordToObsidian(arg1:backend.Word):Promise<backend.ObsidianSaveResult>;

export function SaveWritingToObsidian(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string):Promise<backend.ObsidianSaveResult>;

export function SearchWordsInDB(arg1:string,arg2:number):Promise<Array<backend.Word>>;

export function SetSessionNote(arg1:number,arg2:string):Promise<void>;

export function StartSpeakingRecording():Promise<backend.RecordingStatus>;

export function StopAudio():Promise<void>;

export function StopSpeakingRecording():Promise<backend.RecordingStatus>;

export function TranslateParagraph(arg1:string,arg2:string,arg3:string,arg4:string):Promise<backend.TranslationResult>;

export function TranslateParagraphQuick(arg1:string,arg2:string,arg3:string,arg4:string):Promise<backend.TranslationResult>;

export function UpdateObsidianSrsReview(arg1:string,arg2:string,arg3:number):Promise<void>;
