// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {backend} from '../models';

export function CheckDictation(arg1:string,arg2:string):Promise<backend.DictationResult>;

export function EvaluateWriting(arg1:string,arg2:string,arg3:string):Promise<string>;

export function GetAvailableTopics():Promise<Array<Record<string, string>>>;

export function GetConfig():Promise<backend.Config>;

export function GetDailyIdiom():Promise<backend.Idiom>;

export function GetDailyVocab(arg1:string,arg2:number):Promise<Array<backend.Word>>;

export function GetDictationSentence(arg1:string):Promise<backend.Dictation>;

export function GetQuickQuiz():Promise<backend.Quiz>;

export function GetSavedObsidianVocab():Promise<Array<backend.ObsidianItem>>;

export function GetWritingPrompt(arg1:string):Promise<backend.WritingPrompt>;

export function Greet(arg1:string):Promise<string>;

export function OpenInObsidian(arg1:string):Promise<void>;

export function RecordSrsReview(arg1:number,arg2:number):Promise<void>;

export function SaveAllWordsToObsidian(arg1:Array<backend.Word>):Promise<Array<backend.ObsidianSaveResult>>;

export function SaveConfig(arg1:backend.Config):Promise<void>;

export function SaveWordToObsidian(arg1:backend.Word):Promise<backend.ObsidianSaveResult>;

export function SaveWritingToObsidian(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string):Promise<backend.ObsidianSaveResult>;

export function UpdateObsidianSrsReview(arg1:string,arg2:string,arg3:number):Promise<void>;
