// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CheckDictation(arg1, arg2) {
  return window['go']['main']['App']['CheckDictation'](arg1, arg2);
}

export function CheckGrammarAnswer(arg1, arg2) {
  return window['go']['main']['App']['CheckGrammarAnswer'](arg1, arg2);
}

export function DeleteWordFromObsidian(arg1) {
  return window['go']['main']['App']['DeleteWordFromObsidian'](arg1);
}

export function EvaluateWriting(arg1, arg2, arg3) {
  return window['go']['main']['App']['EvaluateWriting'](arg1, arg2, arg3);
}

export function GetAvailableTopics() {
  return window['go']['main']['App']['GetAvailableTopics']();
}

export function GetConfig() {
  return window['go']['main']['App']['GetConfig']();
}

export function GetDailyIdiom() {
  return window['go']['main']['App']['GetDailyIdiom']();
}

export function GetDailyVocab(arg1, arg2) {
  return window['go']['main']['App']['GetDailyVocab'](arg1, arg2);
}

export function GetDictationCategories() {
  return window['go']['main']['App']['GetDictationCategories']();
}

export function GetDictationLevels() {
  return window['go']['main']['App']['GetDictationLevels']();
}

export function GetDictationSentence(arg1) {
  return window['go']['main']['App']['GetDictationSentence'](arg1);
}

export function GetDictationSentenceFiltered(arg1, arg2, arg3) {
  return window['go']['main']['App']['GetDictationSentenceFiltered'](arg1, arg2, arg3);
}

export function GetDictationSentenceWithExclude(arg1, arg2) {
  return window['go']['main']['App']['GetDictationSentenceWithExclude'](arg1, arg2);
}

export function GetGrammarCategories() {
  return window['go']['main']['App']['GetGrammarCategories']();
}

export function GetGrammarDrill(arg1, arg2, arg3) {
  return window['go']['main']['App']['GetGrammarDrill'](arg1, arg2, arg3);
}

export function GetListeningTopics() {
  return window['go']['main']['App']['GetListeningTopics']();
}

export function GetQuickQuiz() {
  return window['go']['main']['App']['GetQuickQuiz']();
}

export function GetQuickQuizExcluding(arg1) {
  return window['go']['main']['App']['GetQuickQuizExcluding'](arg1);
}

export function GetSavedObsidianVocab() {
  return window['go']['main']['App']['GetSavedObsidianVocab']();
}

export function GetVoicesList() {
  return window['go']['main']['App']['GetVoicesList']();
}

export function GetWordCount() {
  return window['go']['main']['App']['GetWordCount']();
}

export function GetWritingPrompt(arg1) {
  return window['go']['main']['App']['GetWritingPrompt'](arg1);
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function LookupWordInDB(arg1) {
  return window['go']['main']['App']['LookupWordInDB'](arg1);
}

export function OpenInObsidian(arg1) {
  return window['go']['main']['App']['OpenInObsidian'](arg1);
}

export function PlayAudioUrl(arg1, arg2) {
  return window['go']['main']['App']['PlayAudioUrl'](arg1, arg2);
}

export function PlayTTS(arg1, arg2) {
  return window['go']['main']['App']['PlayTTS'](arg1, arg2);
}

export function QueryAI(arg1, arg2) {
  return window['go']['main']['App']['QueryAI'](arg1, arg2);
}

export function RecordSrsReview(arg1, arg2) {
  return window['go']['main']['App']['RecordSrsReview'](arg1, arg2);
}

export function SaveAllWordsToObsidian(arg1) {
  return window['go']['main']['App']['SaveAllWordsToObsidian'](arg1);
}

export function SaveConfig(arg1) {
  return window['go']['main']['App']['SaveConfig'](arg1);
}

export function SaveTranslationToObsidian(arg1, arg2, arg3, arg4, arg5, arg6) {
  return window['go']['main']['App']['SaveTranslationToObsidian'](arg1, arg2, arg3, arg4, arg5, arg6);
}

export function SaveWordToDB(arg1) {
  return window['go']['main']['App']['SaveWordToDB'](arg1);
}

export function SaveWordToObsidian(arg1) {
  return window['go']['main']['App']['SaveWordToObsidian'](arg1);
}

export function SaveWritingToObsidian(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['SaveWritingToObsidian'](arg1, arg2, arg3, arg4, arg5);
}

export function SearchWordsInDB(arg1, arg2) {
  return window['go']['main']['App']['SearchWordsInDB'](arg1, arg2);
}

export function StopAudio() {
  return window['go']['main']['App']['StopAudio']();
}

export function TranslateParagraph(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['TranslateParagraph'](arg1, arg2, arg3, arg4);
}

export function UpdateObsidianSrsReview(arg1, arg2, arg3) {
  return window['go']['main']['App']['UpdateObsidianSrsReview'](arg1, arg2, arg3);
}
